---
dir: fakes/{{ trimPrefix "internal/" .InterfaceDirRelative }}
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.go"
force-file-write: true
pkgname: "mocks"
template: testify
template-data:
  unroll-variadic: true
packages: 
  github.com/corani/unwise/internal/storage:
    interfaces: 
      Storage: {}
