// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/corani/unwise/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// AddBook provides a mock function for the type Storage
func (_mock *Storage) AddBook(ctx context.Context, title string, author string, source string) (storage.Book, error) {
	ret := _mock.Called(ctx, title, author, source)

	if len(ret) == 0 {
		panic("no return value specified for AddBook")
	}

	var r0 storage.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (storage.Book, error)); ok {
		return returnFunc(ctx, title, author, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) storage.Book); ok {
		r0 = returnFunc(ctx, title, author, source)
	} else {
		r0 = ret.Get(0).(storage.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, title, author, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_AddBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBook'
type Storage_AddBook_Call struct {
	*mock.Call
}

// AddBook is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - author string
//   - source string
func (_e *Storage_Expecter) AddBook(ctx interface{}, title interface{}, author interface{}, source interface{}) *Storage_AddBook_Call {
	return &Storage_AddBook_Call{Call: _e.mock.On("AddBook", ctx, title, author, source)}
}

func (_c *Storage_AddBook_Call) Run(run func(ctx context.Context, title string, author string, source string)) *Storage_AddBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Storage_AddBook_Call) Return(book storage.Book, err error) *Storage_AddBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *Storage_AddBook_Call) RunAndReturn(run func(ctx context.Context, title string, author string, source string) (storage.Book, error)) *Storage_AddBook_Call {
	_c.Call.Return(run)
	return _c
}

// AddHighlight provides a mock function for the type Storage
func (_mock *Storage) AddHighlight(ctx context.Context, b storage.Book, text string, note string, chapter string, location int, url string) (storage.Highlight, error) {
	ret := _mock.Called(ctx, b, text, note, chapter, location, url)

	if len(ret) == 0 {
		panic("no return value specified for AddHighlight")
	}

	var r0 storage.Highlight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.Book, string, string, string, int, string) (storage.Highlight, error)); ok {
		return returnFunc(ctx, b, text, note, chapter, location, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.Book, string, string, string, int, string) storage.Highlight); ok {
		r0 = returnFunc(ctx, b, text, note, chapter, location, url)
	} else {
		r0 = ret.Get(0).(storage.Highlight)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.Book, string, string, string, int, string) error); ok {
		r1 = returnFunc(ctx, b, text, note, chapter, location, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_AddHighlight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHighlight'
type Storage_AddHighlight_Call struct {
	*mock.Call
}

// AddHighlight is a helper method to define mock.On call
//   - ctx context.Context
//   - b storage.Book
//   - text string
//   - note string
//   - chapter string
//   - location int
//   - url string
func (_e *Storage_Expecter) AddHighlight(ctx interface{}, b interface{}, text interface{}, note interface{}, chapter interface{}, location interface{}, url interface{}) *Storage_AddHighlight_Call {
	return &Storage_AddHighlight_Call{Call: _e.mock.On("AddHighlight", ctx, b, text, note, chapter, location, url)}
}

func (_c *Storage_AddHighlight_Call) Run(run func(ctx context.Context, b storage.Book, text string, note string, chapter string, location int, url string)) *Storage_AddHighlight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.Book
		if args[1] != nil {
			arg1 = args[1].(storage.Book)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *Storage_AddHighlight_Call) Return(highlight storage.Highlight, err error) *Storage_AddHighlight_Call {
	_c.Call.Return(highlight, err)
	return _c
}

func (_c *Storage_AddHighlight_Call) RunAndReturn(run func(ctx context.Context, b storage.Book, text string, note string, chapter string, location int, url string) (storage.Highlight, error)) *Storage_AddHighlight_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHighlight provides a mock function for the type Storage
func (_mock *Storage) DeleteHighlight(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHighlight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_DeleteHighlight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHighlight'
type Storage_DeleteHighlight_Call struct {
	*mock.Call
}

// DeleteHighlight is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Storage_Expecter) DeleteHighlight(ctx interface{}, id interface{}) *Storage_DeleteHighlight_Call {
	return &Storage_DeleteHighlight_Call{Call: _e.mock.On("DeleteHighlight", ctx, id)}
}

func (_c *Storage_DeleteHighlight_Call) Run(run func(ctx context.Context, id int)) *Storage_DeleteHighlight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_DeleteHighlight_Call) Return(err error) *Storage_DeleteHighlight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_DeleteHighlight_Call) RunAndReturn(run func(ctx context.Context, id int) error) *Storage_DeleteHighlight_Call {
	_c.Call.Return(run)
	return _c
}

// ListBooks provides a mock function for the type Storage
func (_mock *Storage) ListBooks(ctx context.Context, lt time.Time, gt time.Time) ([]storage.Book, error) {
	ret := _mock.Called(ctx, lt, gt)

	if len(ret) == 0 {
		panic("no return value specified for ListBooks")
	}

	var r0 []storage.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]storage.Book, error)); ok {
		return returnFunc(ctx, lt, gt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []storage.Book); ok {
		r0 = returnFunc(ctx, lt, gt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, lt, gt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_ListBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBooks'
type Storage_ListBooks_Call struct {
	*mock.Call
}

// ListBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - lt time.Time
//   - gt time.Time
func (_e *Storage_Expecter) ListBooks(ctx interface{}, lt interface{}, gt interface{}) *Storage_ListBooks_Call {
	return &Storage_ListBooks_Call{Call: _e.mock.On("ListBooks", ctx, lt, gt)}
}

func (_c *Storage_ListBooks_Call) Run(run func(ctx context.Context, lt time.Time, gt time.Time)) *Storage_ListBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_ListBooks_Call) Return(books []storage.Book, err error) *Storage_ListBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *Storage_ListBooks_Call) RunAndReturn(run func(ctx context.Context, lt time.Time, gt time.Time) ([]storage.Book, error)) *Storage_ListBooks_Call {
	_c.Call.Return(run)
	return _c
}

// ListHighlights provides a mock function for the type Storage
func (_mock *Storage) ListHighlights(ctx context.Context, lt time.Time, gt time.Time) ([]storage.Highlight, error) {
	ret := _mock.Called(ctx, lt, gt)

	if len(ret) == 0 {
		panic("no return value specified for ListHighlights")
	}

	var r0 []storage.Highlight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]storage.Highlight, error)); ok {
		return returnFunc(ctx, lt, gt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []storage.Highlight); ok {
		r0 = returnFunc(ctx, lt, gt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Highlight)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, lt, gt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_ListHighlights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHighlights'
type Storage_ListHighlights_Call struct {
	*mock.Call
}

// ListHighlights is a helper method to define mock.On call
//   - ctx context.Context
//   - lt time.Time
//   - gt time.Time
func (_e *Storage_Expecter) ListHighlights(ctx interface{}, lt interface{}, gt interface{}) *Storage_ListHighlights_Call {
	return &Storage_ListHighlights_Call{Call: _e.mock.On("ListHighlights", ctx, lt, gt)}
}

func (_c *Storage_ListHighlights_Call) Run(run func(ctx context.Context, lt time.Time, gt time.Time)) *Storage_ListHighlights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_ListHighlights_Call) Return(highlights []storage.Highlight, err error) *Storage_ListHighlights_Call {
	_c.Call.Return(highlights, err)
	return _c
}

func (_c *Storage_ListHighlights_Call) RunAndReturn(run func(ctx context.Context, lt time.Time, gt time.Time) ([]storage.Highlight, error)) *Storage_ListHighlights_Call {
	_c.Call.Return(run)
	return _c
}

// ListHighlightsByBook provides a mock function for the type Storage
func (_mock *Storage) ListHighlightsByBook(ctx context.Context, bookID int) ([]storage.Highlight, error) {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for ListHighlightsByBook")
	}

	var r0 []storage.Highlight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]storage.Highlight, error)); ok {
		return returnFunc(ctx, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []storage.Highlight); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Highlight)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_ListHighlightsByBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHighlightsByBook'
type Storage_ListHighlightsByBook_Call struct {
	*mock.Call
}

// ListHighlightsByBook is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID int
func (_e *Storage_Expecter) ListHighlightsByBook(ctx interface{}, bookID interface{}) *Storage_ListHighlightsByBook_Call {
	return &Storage_ListHighlightsByBook_Call{Call: _e.mock.On("ListHighlightsByBook", ctx, bookID)}
}

func (_c *Storage_ListHighlightsByBook_Call) Run(run func(ctx context.Context, bookID int)) *Storage_ListHighlightsByBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_ListHighlightsByBook_Call) Return(highlights []storage.Highlight, err error) *Storage_ListHighlightsByBook_Call {
	_c.Call.Return(highlights, err)
	return _c
}

func (_c *Storage_ListHighlightsByBook_Call) RunAndReturn(run func(ctx context.Context, bookID int) ([]storage.Highlight, error)) *Storage_ListHighlightsByBook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHighlight provides a mock function for the type Storage
func (_mock *Storage) UpdateHighlight(ctx context.Context, h storage.Highlight) (storage.Highlight, error) {
	ret := _mock.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHighlight")
	}

	var r0 storage.Highlight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.Highlight) (storage.Highlight, error)); ok {
		return returnFunc(ctx, h)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.Highlight) storage.Highlight); ok {
		r0 = returnFunc(ctx, h)
	} else {
		r0 = ret.Get(0).(storage.Highlight)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.Highlight) error); ok {
		r1 = returnFunc(ctx, h)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_UpdateHighlight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHighlight'
type Storage_UpdateHighlight_Call struct {
	*mock.Call
}

// UpdateHighlight is a helper method to define mock.On call
//   - ctx context.Context
//   - h storage.Highlight
func (_e *Storage_Expecter) UpdateHighlight(ctx interface{}, h interface{}) *Storage_UpdateHighlight_Call {
	return &Storage_UpdateHighlight_Call{Call: _e.mock.On("UpdateHighlight", ctx, h)}
}

func (_c *Storage_UpdateHighlight_Call) Run(run func(ctx context.Context, h storage.Highlight)) *Storage_UpdateHighlight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.Highlight
		if args[1] != nil {
			arg1 = args[1].(storage.Highlight)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_UpdateHighlight_Call) Return(highlight storage.Highlight, err error) *Storage_UpdateHighlight_Call {
	_c.Call.Return(highlight, err)
	return _c
}

func (_c *Storage_UpdateHighlight_Call) RunAndReturn(run func(ctx context.Context, h storage.Highlight) (storage.Highlight, error)) *Storage_UpdateHighlight_Call {
	_c.Call.Return(run)
	return _c
}
