name: docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches: ['master']
    tags: ['v*']
  pull_request: 
    branches: ['master']

env: 
  REGISTRY: ghcr.io 
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha

      - uses: docker/build-push-action@v5
        with: 
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | 
            VERSION=${{ github.ref_name }}
