name: release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags: ['v*']

permissions: 
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - uses: FranzDiebold/github-env-vars-action@v2

      - uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          excludeLabels: 'duplicate,question,invalid,wontfix,release'
          addSections: '{"documentation":{"prefix":"**Documentation Updates:**","labels":["documentation"]}}'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Changelog for ${{ env.CI_REF_NAME }}
          file_pattern: CHANGELOG.md

  release:
    runs-on: ubuntu-latest
    needs: [changelog]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: FranzDiebold/github-env-vars-action@v2

      - uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ env.CI_REF_NAME }}
          path: CHANGELOG.md

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.CI_REF_NAME }}
          name: ${{ env.CI_REF_NAME }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
